# Generated by Django 2.1.7 on 2019-02-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_auto_20190225_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='student', to='Student.Student'),
        ),
    ]
