# Generated by Django 2.1.7 on 2019-02-25 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_auto_20190225_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 2, 25, 15, 1, 28, 250295), null=True),
        ),
    ]
