# Generated by Django 2.1.7 on 2019-03-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_auto_20190303_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='course',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
