# Generated by Django 2.1.7 on 2019-03-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_auto_20190313_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(blank=True, limit_choices_to=5, related_name='course', to='Student.Course'),
        ),
    ]
