# Generated by Django 2.1.7 on 2019-03-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0011_auto_20190313_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='course', to='Student.Course'),
        ),
    ]
